#http listener configuration
  http.listener.host=0.0.0.0
  http.listener.port=8081
  http.listener.path=/api/*
  
#http database configuration
  database.host=iltdb.learn.mulesoft.com
  database.port=3306
  database.user=mule
  database.password=mule
  database.database=training